server:
  port: 8080
  env: "development"
  timeout: 30s

auth:
  jwt_secret: "your_secure_secret_here"
  access_token_expiry: 15m
  refresh_token_expiry: 168h  # 7 дней

database:
  postgres:
    host: "postgres"
    port: 5432
    user: "api_gateway"
    password: "secure_password"
    name: "photo_booking"
    max_connections: 50
  redis:
    addr: "redis:6379"
    password: ""
    db: 0

services:
  booking_service: "booking-service:50051"
  schedule_service: "schedule-service:50052"
  notification_service: "notification-service:50053"

logging:
  level: "debug"
  format: "json"

monitoring:
  prometheus_port: 9090
  enable_metrics: true